#Thanks http://kiwipsum.com/generate/p/9
import random

def give_me_text(min_lenght, paragraph_start, paragraph_end):
	retval = ""
	while len(retval) < min_lenght:
		retval += paragraph_start
		retval += random.choice(paragraphs)
		retval += paragraph_end
	return retval

paragraphs = [

"""A slice of heaven. Till the cows come home, this outrageously awesome morepork is as snarky as a nuclear-free tiki tour. Mean while, in the sleepout, The Hungery Caterpilar and Hercules Morse, as big as a horse were up to no good with a bunch of hard yakka fellas. The tapu force of his chundering was on par with Mr Whippy's tip-top Monopoly, the New Zealand version with Queen Street and stuff. Put the jug on will you bro, all these pearler chilly bins can wait till later. The first prize for whale watching goes to... Uncle Bully and his cracker vivid, what a sad guy. Bro, All Blacks are really thermo-nuclear good with fully sick girl guide biscuits, aye. You have no idea how carked it our crook chocolate fishes were aye. Every time I see those stuffed Longest Drinks in Town it's like the sausage sizzle all over again aye, no wucken forries. Anyway, Tama is just Cardigan Bay in disguise, to find the true meaning of life, one must start making scones with the pinapple lump, mate.""", 

"""After the kiwiburger is flogged, you add all the choice jerseys to the native vegetable you've got yourself a meal. Fair suck of the sav. Technology has allowed chocka full scarfies to participate in the global conversation of same same but different craft supplies. The next Generation of primo munters have already rooted over at Pack n' Save. What's the hurry James Cook? There's plenty of Jafas in the Four Square supermarket. Castle Hill holds the most solid rimu community in the country.. Hairy Maclary from Donaldson's Dairy was rooting when the sweet as playing rugby event occured. Cool story bro, this heaps good brain drain is as beautiful as a mint. Mean while, in the pub, Fred Dagg and Bazza were up to no good with a bunch of cool tomato sauces. The beaut force of his packing a sad was on par with The Topp Twins's good as jelly tip icecream. Put the jug on will you bro, all these stoked giant wekas can wait till later.""",

"""The first prize for preparing the hungi goes to... the Armed Offenders Squad and his naff cookie time, what a hottie. Bro, pauas are really pretty suss good with paru rugby balls, aye. You have no idea how sweet our bung mates were aye. Every time I see those shithouse lengths of number 8 wire it's like Mt Cook all over again aye, rack off. Anyway, Rangi is just Mrs Falani in disguise, to find the true meaning of life, one must start boiling-up with the kea, mate. After the weka is jumped the ditch, you add all the rip-off utes to the Bell Bird you've got yourself a meal. I'm not here to frack spiders. Technology has allowed wicked hongis to participate in the global conversation of rip-off Tuis.""",

"""The next Generation of hammered goons have already cooked over at the beach. What's the hurry John Key? There's plenty of Swanndris in the marae. Lake Taupo holds the most dodgy community in the country.. Lomu was reffing the game when the random pashing event occured. Can't handle the jandle, this pretty suss misses is as sweet as as a kiwi as hokey pokey. Mean while, in West Auckland, Manus Morissette and Dr Ropata were up to no good with a bunch of buzzy stubbiess. The bloody force of his wobbling was on par with Rhys Darby's flat stick sheep. Put the jug on will you bro, all these chronic hangis can wait till later. The first prize for cooking up a feed goes to... a Taniwha and his stink trotie, what a ankle biter.""",

"""Bro, pieces of pounamu are really epic good with hard case Silver Ferns, aye. Cook your own eggs Jake, chur bro. You have no idea how rough as guts our mean as pavlovas were aye. Every time I see those beached as kais it's like Rangitoto Island all over again aye, left my scooter outside the dairy. Anyway, Maui is just Spot, the Telecom dog in disguise, to find the true meaning of life, one must start rooting with the toasted sandwich, mate.""",

"""After the wifebeater singlet is munted, you add all the outrageously awesome cans of Watties Baked Beans to the pohutukawa you've got yourself a meal. Technology has allowed snarky pukekos to participate in the global conversation of nuclear-free lamingtons. Those bloody Jaffa's, no worries, take the piss. The next Generation of hard yakka dole bludgers have already packed a sad over at the tinny house. What's the hurry some uni student? There's plenty of kiwis in the bushes. The dairy holds the most tapu community in the country.. Jim Hickey was whinging when the tip-top munting event occured. Where's the chips bro, this pearler cuzzie is as cracker as a thermo-nuclear holden. Mean while, in South Pacific, Jonah Lomu and Sir Edmond Hillary were up to no good with a bunch of fully sick whitebait fritters. The carked it force of his cruising for a brusing was on par with James and the Giant Peach's crook L&P. Put the jug on will you bro, all these stuffed quater-acre patchs can wait till later.""",

"""The first prize for frying up goes to... Helen Clarke and his choice old man's beard, what a stink buzz. Bro, Grandpa's slippers are really chocka full good with same same but different Edmonds Cook Books, aye. You have no idea how primo our solid rimu pieces of cheese on toast were aye. Every time I see those sweet as sections it's like the fish n' chip shop all over again aye, howsit goin. Anyway, The Hungery Caterpilar is just Hercules Morse, as big as a horse in disguise, to find the true meaning of life, one must start burning my Vogel's with the Hei-tiki, mate. Bro, how's ya father. After the packet of Wheetbix is skived off, you add all the heaps good bottles of milk to the whanau you've got yourself a meal. Technology has allowed beautiful sheilas to participate in the global conversation of mint twink sticks. The next Generation of cool manuses have already flogged over at the op shop. What's the hurry Mr Whippy? There's plenty of foreshore and seabed issues in the wop wops. Smoko time holds the most beaut community in the country.. Uncle Bully was skiving off when the good as chundering event occured.""",

"""Sort your drinking out, this stoked seabed is as naff as a pretty suss chick. Mean while, in Queenstown, Tama and Cardigan Bay were up to no good with a bunch of paru onion dips. The sweet force of his whale watching was on par with James Cook's bung slipper. Speights, pride of the south for over 100 years, just a little bit, ay. Put the jug on will you bro, all these shithouse wet blankets can wait till later. The first prize for making scones goes to... Hairy Maclary from Donaldson's Dairy and his rip-off marmite shortage, what a egg. Bro, boxes of fluffies are really wicked good with rip-off mince pies, aye. You have no idea how hammered our dodgy gumboots were aye.""",

"""Every time I see those random pikelets it's like the sausage sizzle all over again aye, you don't know his story, bro. Anyway, Fred Dagg is just Bazza in disguise, to find the true meaning of life, one must start rooting with the fella, mate. After the Monopoly, the New Zealand version with Queen Street and stuff is rooted, you add all the pretty suss chilly bins to the vivid you've got yourself a meal. Technology has allowed sweet as kai moanas to participate in the global conversation of kiwi as All Blacks. The next Generation of buzzy sad guys have already jumped the ditch over at Pack n' Save.""",

"""Kia ora.. Spit the dummy, this shithouse kumara is as primo as a stuffed. Mean while, in the bushes, James Cook and Fred Dagg were up to no good with a bunch of random cookie times. The hard yakka force of his frying up was on par with The Hungery Caterpilar's fully sick kai. Put the jug on will you bro, all these pearler Grandpa's slippers can wait till later. The first prize for preparing the hungi goes to... James and the Giant Peach and his pretty suss foreshore and seabed issue, what a hottie. Bro, cans of Watties Baked Beans are really dodgy good with solid rimu troties, aye. You have no idea how choice our nuclear-free pair of slippers were aye. Every time I see those cool boxes of fluffies it's like Lake Taupo all over again aye, no wucken forries. Anyway, The Topp Twins is just Jonah Lomu in disguise, to find the true meaning of life, one must start packing a sad with the Hei-tiki, mate. After the lamington is cooked, you add all the rip-off onion dips to the ute you've got yourself a meal. Technology has allowed crook blokes to participate in the global conversation of buzzy packets of Wheetbix. You're not in Guatemala now.""",

"""The next Generation of epic sad guys have already rooted over at the dairy. What's the hurry a Taniwha? There's plenty of bottles of milk in the pub. Pack n' Save holds the most hammered community in the country.. Dr Ropata was burning my Vogel's when the tapu boiling-up event occured. Till the cows come home, this mean as brain drain is as chronic as a flat stick kai moana. Nek minnit, pull a sickie, but. Mean while, in behind the bicycle shed, Rangi and Jim Hickey were up to no good with a bunch of rip-off hangis. The bloody force of his whinging was on par with some uni student's stink marmite shortage. Put the jug on will you bro, all these mint Edmonds Cook Books can wait till later. The first prize for cooking up a feed goes to... Manus Morissette and his naff rugby ball, what a stink buzz.""",

"""O for awesome, don't be a egg, across the ditch. Bro, pauas are really snarky good with wicked whanaus, aye. You have no idea how beached as our beautiful kiwiburgers were aye. Every time I see those thermo-nuclear stubbies it's like the sausage sizzle all over again aye, oh stink buzz. Anyway, Uncle Bully is just the Armed Offenders Squad in disguise, to find the true meaning of life, one must start making scones with the jelly tip icecream, mate. After the mince pie is skived off, you add all the same same but different toasted sandwiches to the Bell Bird you've got yourself a meal. Technology has allowed hard case cuzzies to participate in the global conversation of stoked native vegetables. The next Generation of carked it ankle biters have already flogged over at the op shop. What's the hurry John Key? There's plenty of wekas in Queenstown.""",

"""Smoko time holds the most sweet community in the country.. Yeah nah, giz a toke bro, not even au. Mrs Falani was whale watching when the kiwi as wobbling event occured. Cook your own eggs Jake, this bung hongi is as paru as a cracker seabed. Mean while, in Hamilton, Mr Whippy and Hairy Maclary from Donaldson's Dairy were up to no good with a bunch of sweet as pinapple lumps.""",

"""The pretty suss force of his skiving off was on par with Bazza's heaps good mate. Put the jug on will you bro, all these chocka full old man's beards can wait till later. The first prize for rooting goes to... Maui and his rough as guts section, what a manus. Bro, vivids are really outrageously awesome good with tip-top Jafas, aye. You have no idea how sweet as our beaut pieces of pounamu were aye. Every time I see those good as quater-acre patches it's like the fish n' chip shop all over again aye, cool story bro. Anyway, Cardigan Bay is just Tama in disguise, to find the true meaning of life, one must start rooting with the pohutukawa, mate. After the Swanndri is packed a sad, you add all the shithouse chilly bins to the cheese on toast you've got yourself a meal. Technology has allowed primo scarfies to participate in the global conversation of stuffed gumboots. The next Generation of random goons have already jumped the ditch over at Castle Hill. Not many, if any, reckon ya got a sheep loose in you're top paddock mate. What's the hurry Sir Edmond Hillary? There's plenty of jerseys in a waka.""",

"""The beach holds the most hard yakka community in the country.. Internalizing a really complicated situation, I was just at home having some dots...., bro. Lomu was reffing the game when the fully sick pashing event occured. Do you happen to have a bucket or a hose bro?, this pearler treaty is as pretty suss as a dodgy misses. Throw a wobbly. Mean while, in the sleepout, Helen Clarke and Hercules Morse, as big as a horse were up to no good with a bunch of solid rimu Longest Drink in Towns. True that, chur bro, where's the chips bro. The choice force of his playing rugby was on par with Rhys Darby's nuclear-free whitebait fritter. Put the jug on will you bro, all these cool Silver Ferns can wait till later. The first prize for chundering goes to... Spot, the Telecom dog and his rip-off pavlova, what a egg.""",

"""Bro, All Blacks are really crook good with buzzy fellas, aye. You have no idea how epic our hammered twink sticks were aye. Every time I see those tapu kiwis it's like Mt Cook all over again aye, bugger. Anyway, James Cook is just Fred Dagg in disguise, to find the true meaning of life, one must start munting with the giant weka, mate. Can I arks you a question, I'd slam that clam, cook me some eggs. After the kea is munted, you add all the mean as chocolate fishes to the Tui you've got yourself a meal.""",

"""Technology has allowed chronic Undie 500s to participate in the global conversation of flat stick wet blankets. The next Generation of rip-off munters have already cooked over at Rangitoto Island. What's the hurry The Hungery Caterpilar? There's plenty of bottles of L&P in West Auckland. The tinny house holds the most bloody community in the country.. James and the Giant Peach was cruising for a brusing when the stink frying up event occured. Rack off, this mint housie is as naff as a snarky pukeko. Mean while, in The Naki, The Topp Twins and Jonah Lomu were up to no good with a bunch of wicked craft suppliess.""",

"""The beached as force of his preparing the hungi was on par with a Taniwha's beautiful tomato sauce. Put the jug on will you bro, all these thermo-nuclear Monopoly, the New Zealand version with Queen Street and stuffs can wait till later. The first prize for packing a sad goes to... Dr Ropata and his same same but different length of number 8 wire, what a dole bludger. Bro, herd of sheep are really hard case good with stoked girl guide biscuits, aye. You have no idea how carked it our sweet pikelets were aye. Every time I see those kiwi as wifebeater singlets it's like Lake Taupo all over again aye, Oh no! I'm beached as. Anyway, Rangi is just Jim Hickey in disguise, to find the true meaning of life, one must start burning my Vogel's with the cookie time, mate."""

]